# compose.yml
services:
  app:
    image: app-image
    container_name: app-container
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    tty: true
